#!/bin/bash

AUXDIR=aux
if [ $# -eq 0 ]
then
  echo "No arguments supplied"
  exit
fi
DIR=$(echo $1 | sed 's/\///')
if [ -f $DIR/main.tex ]
then
  echo Cleaning $DIR
  rm -vf $AUXDIR/$1.*
  touch $DIR/main.tex
elif [ $1 = "bak" ]
then
  echo "Cleaning .bak files"
  rm -v */*.bak
else
  echo "clean help"
  echo "Clean a specific subdirectory and make ready for remaking"
fi


