#!/bin/bash

AUXDIR=aux
if [ $# -eq 0 ]
then
  echo "No arguments supplied"
  exit
fi
DIR=$(echo $1 | sed 's/\///')
rm -vf $AUXDIR/$1.*
if [ -f $DIR/main.tex ]
then
  echo Cleaning $DIR
  touch $DIR/main.tex
else
  echo "clean help"
  echo "Clean a specific subdirectory and make ready for remaking"
fi

